otel_bundle:
  tracer_name:  '%otel_tracer_name%'
  service_name: '%otel_service_name%'
  instrumentations:
    - 'Macpaw\SymfonyOtelBundle\Instrumentation\ExecutionTimeInstrumentation'
    - 'Macpaw\SymfonyOtelBundle\Instrumentation\CQRSHookInstrumentation'
