services:
  _defaults:
    autowire: true
    autoconfigure: true

  Macpaw\SymfonyOtelBundle\Span\ExecutionTimeSpanTracer:
    tags:
      - { name: 'kernel.event_subscriber' }
    arguments:
      $tracerName: '%otel_bundle.tracer_name%'

  Macpaw\SymfonyOtelBundle\Service\TraceService:
    arguments:
      $tracerProvider: '@OpenTelemetry\SDK\Trace\TracerProviderInterface'

  otpl.tracerProviderFactory:
    class: OpenTelemetry\SDK\Trace\TracerProviderFactory

  OpenTelemetry\SDK\Trace\TracerProviderInterface:
    class: OpenTelemetry\SDK\Trace\TracerProvider
    factory: [ '@otpl.tracerProviderFactory', 'create' ]
    tags:
      - { name: 'otpl.tracerProvider' }

  OpenTelemetry\Context\Propagation\TextMapPropagatorInterface:
    class: OpenTelemetry\API\Trace\Propagation\TraceContextPropagator
