services:
  # Tempo - OpenTelemetry traces backend
  tempo:
    user: root
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    networks:
      - otel-network

  # Grafana - for viewing traces
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:rw
    depends_on:
      - tempo
    networks:
      - otel-network

  # PHP application for testing
  php-app:
    user: root
    build:
      context: .
      dockerfile: docker/php/Dockerfile_grpc # or docker/php/Dockerfile_grpc
    volumes:
      - .:/var/www/html:rw
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:rw
    environment:
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317 # Used tempo directly for simplicity, or you may use otel-collector - http://otel-collector:4317 (external ports: 14317/14318)
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc # or grpc
      OTEL_SERVICE_NAME: symfony-otel-app
      OTEL_TRACER_NAME: symfony-otel-bundle
      OTEL_RESOURCE_ATTRIBUTES: service.name=symfony-otel-app
      OTEL_PROPAGATORS: tracecontext,baggage
      OTEL_LOG_LEVEL: debug
    depends_on:
      - tempo
    networks:
      - otel-network
volumes:
  tempo-data:
  grafana-data:

networks:
  otel-network:
    driver: bridge
