services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  querybus.query.instrumentation:
    class: Macpaw\SymfonyOtelBundle\Instrumentation\ClassHookInstrumentation
    arguments:
      $className: 'App\Infrastructure\MessageBus\QueryBus'
      $methodName: 'query'
    calls:
      - [ 'addMiddleware', ['@App\Decorator\ExampleAttributesSpanMiddleware'] ]
      - [ 'addMiddleware', ['@App\Decorator\ExampleEventsSpanMiddleware'] ]

  querybus.dispatch.instrumentation:
    class: Macpaw\SymfonyOtelBundle\Instrumentation\ClassHookInstrumentation
    arguments:
      $className: 'App\Infrastructure\MessageBus\QueryBus'
      $methodName: 'dispatch'
    calls:
      - [ 'addMiddleware', ['@App\Decorator\ExampleLogsSpanMiddleware'] ]
