otel_bundle:
  tracer_name: '%env(OTEL_TRACER_NAME)%'
  service_name: '%env(OTEL_SERVICE_NAME)%'
  instrumentations:
    - 'App\Instrumentation\ExampleHookInstrumentation'
    - 'Macpaw\SymfonyOtelBundle\Instrumentation\SyncQueryBusHookInstrumentation'
    - 'Macpaw\SymfonyOtelBundle\Instrumentation\AsyncQueryBusHookInstrumentation' 